baseURL = "https://www.zmt.ac.cn"
languageCode = "en-us"
theme = "smigle"
title = "ZMT"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "daily"
    name = "Daily"
    url = "/daily/"
    weight = 3

  [[menu.main]]
    identifier = "read"
    name = "Read"
    url = "/read/"
    weight = 4

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 5

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 6

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 7
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 8

[params]
  abbrDateFmt = "Jan 2"
  author = "Blog Author"
  brandIconFile = "images/brandIcon.svg"
  dateFmt = "2006-01-02"

  ## Options for overriding theme or page defaults
  # customStylesheets = ["css/custom.css"]  # Use to override theme styles, like logo size
  # readingSpeed = 600  # Use to set custom reading speed
  # readingSpeedMin = 25  # Use to set custom reading speed range
  # readingSpeedMax = 175  # Use to set custom reading speed range

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/zmtn"

  [[params.social]]
    name = "Email"
    url = "mailto:likui@zmt.ac.cn"

  [[params.social]]
    name = "Quizlet"
    url = "https://quizlet.com/zmtar"

  [[params.social]]
    name = "Reddit"
    url = "https://www.reddit.com/user/vlikuiv"

  [[params.social]]
    name = "StackOverflow"
    url = "https://stackoverflow.com/users/23910950/likui"

  subtitle = "Many a little makes a mackle"
 # config.toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

